name: Release

on:
  push:
    tags:
      - 'v*.*.*' # vMAJOR.MINOR.PATCH
      - 'v*.*.*-*' # vMAJOR.MINOR.PATCH-(beta, alpha, rc)

jobs:
  release:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout código
        uses: actions/checkout@v4

      - name: Criar Release no GitHub
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ github.ref }}
          generate_release_notes: true
          prerelease: ${{ startsWith(github.ref, 'refs/tags/v') && contains(github.ref, '-') }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
