name: Release

on:
  push:
    tags:
      - 'v*.*.*' # vMAJOR.MINOR.PATCH

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout código
        uses: actions/checkout@v4

      - name: Criar Release
        uses: softprops/action-gh-release@v2
        with:
          generate_release_notes: true
